# Name of your quickstart as shown on the website
name: New Relic Audit
description: Dashboard to analyse the New Relic Audit events.

# Optional: Authors of the quickstart
authors:
    - Swati Joshi
